# Generated by Django 4.2 on 2023-07-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Trainer'), ('3', 'Customer')], default=1, max_length=50),
        ),
    ]
